# Generated by Django 5.1.2 on 2024-10-25 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyReportMorning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sleep_time", models.TimeField()),
                ("wake_time", models.TimeField()),
                ("sleep_quality", models.CharField(max_length=150)),
                ("had_dinner_yesterday", models.CharField(max_length=10)),
                ("had_breakfast_today", models.CharField(max_length=10)),
                ("medicine_time", models.CharField(max_length=10)),
                ("current_condition", models.CharField(max_length=10)),
                ("current_condition_other", models.TextField(blank=True, null=True)),
                ("anxiety_level", models.CharField(max_length=10)),
                ("current_emotion", models.CharField(max_length=10)),
                ("communication_willingness", models.CharField(max_length=10)),
                ("physical_condition", models.CharField(max_length=10)),
                ("concentration_level", models.CharField(max_length=10)),
                ("physical_discomfort", models.CharField(max_length=10)),
                ("self_esteem", models.CharField(max_length=10)),
                ("willingness_to_depend", models.CharField(max_length=10)),
                ("feeling_needed", models.CharField(max_length=10)),
                ("other_symptoms", models.TextField(blank=True, null=True)),
                ("need_work_accommodation", models.CharField(max_length=20)),
                (
                    "need_work_accommodation_other",
                    models.TextField(blank=True, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("recovery_routine", models.TextField(blank=True, null=True)),
                ("emotional_stability_after_self", models.IntegerField()),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("general", "General")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("answer_type", models.CharField(default="未指定", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_datetime", models.DateTimeField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[("morning", "Morning"), ("evening", "Evening")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
            ],
            options={
                "db_table": "daily_reports",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyReportAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("threshold_value", models.FloatField()),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.dailyreport",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.questionnaire",
                    ),
                ),
            ],
            options={
                "db_table": "daily_report_answers",
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=100)),
                ("option_value", models.IntegerField()),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.questionnaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnaireThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threshold_min", models.IntegerField(blank=True, null=True)),
                ("threshold_max", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.questionnaire",
                    ),
                ),
            ],
            options={
                "db_table": "questionnaire_thresholds",
                "unique_together": {("employee", "questionnaire")},
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("exact_value", models.FloatField(blank=True, null=True)),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[
                            ("min", "Minimum Value"),
                            ("max", "Maximum Value"),
                            ("exact", "Exact Value"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.questionnaire",
                    ),
                ),
            ],
            options={
                "db_table": "thresholds",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "questionnaire"),
                        name="unique_employee_questionnaire",
                    )
                ],
            },
        ),
    ]
