# Generated by Django 5.1.2 on 2024-10-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "questionnaire_categories",
            },
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="questionnaire",
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="type",
            field=models.CharField(
                choices=[("morning", "Morning"), ("evening", "Evening")], max_length=10
            ),
        ),
        migrations.AlterModelTable(
            name="questionnaire",
            table="questionnaires",
        ),
        migrations.AlterModelTable(
            name="questionnaireoption",
            table="questionnaire_options",
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.questionnairecategory",
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Threshold",
        ),
    ]
