# Generated by Django 5.1.2 on 2024-10-22 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dailyreport_dailyreportanswer_employee_questionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('exact_value', models.FloatField(blank=True, null=True)),
                ('threshold_type', models.CharField(choices=[('min', 'Minimum'), ('max', 'Maximum'), ('exact', 'Exact')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questionnaire')),
            ],
            options={
                'db_table': 'thresholds',
                'unique_together': {('employee', 'questionnaire')},
            },
        ),
    ]
